### ISSUE TITLE
Version 3.3.1 does not work with xcode build

### ISSUE THREAD

**Issue by stefanoScalzo** [triniwiz/nativescript-socketio#101]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When running `tns build ios` after a fresh `ns clean` the build fails
Do note version 3.0.0 does not
This needs to be fixed as many are dependant on these sockets 

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?
IOS
iPhone 11
### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 7.0.11
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
there is no such thing since nativescript 7
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
android 7.0.1
ios 7.1.0
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
3.3.1
### Please, tell us how to recreate the issue in as much detail as possible. 
Create a nativescript project, install nativescript-socketio version 3.3.1 and up

### Is there any code involved? 
```
Error: There is no appropriate source code format in '/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/nativescript-socketio' entry-point.
    at DependencyResolver.getEntryPointFormatInfo (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_resolver.js:164:19)
    at DependencyResolver.getEntryPointWithDependencies (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_resolver.js:70:39)
    at EntryPointCollector.walkDirectoryForPackages (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:47:52)
    at EntryPointCollector.walkDirectoryForPackages (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:75:79)
    at /Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:124:100
    at Object.trackDuration (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/utils.js:93:22)
    at ProgramBasedEntryPointFinder.walkBasePathForPackages (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:124:39)
    at ProgramBasedEntryPointFinder.findOrLoadEntryPoints (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:89:34)
    at ProgramBasedEntryPointFinder.getEntryPointWithDeps (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:66:36)
    at ProgramBasedEntryPointFinder.TracingEntryPointFinder.findEntryPoints (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/tracing_entry_point_finder.js:48:47)
/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack-cli/bin/cli.js:281
                                throw err;
                                ^

Error: NGCC failed.
    at NgccProcessor.process (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@ngtools/webpack/src/ngcc_processor.js:129:19)
    at /Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:593:31
    at SyncHook.eval [as call] (eval at create (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at webpack (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack/lib/webpack.js:55:30)
    at processOptions (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack-cli/bin/cli.js:272:16)
    at /Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/yargs/yargs.js:576:18)
    at /Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/stefanoscalzo/Library/Mobile Documents/com~apple~CloudDocs/GitHub/Puggum/frontend/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Executing webpack failed with exit code 1.
```

**Comment by triniwiz** [comment]
it's now `@triniwiz/nativescript-socketio`
